apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: registry.cn-zhangjiakou.aliyuncs.com/cloud-proj/cloud-proj-yaml:1.0.0
          ports:
            - containerPort: 8080
